osx_image: xcode9.2
language: swift
script:
    - xcodebuild clean test -project CITreeView.xcodeproj -scheme CITreeView -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
